export const categories = [
    {
      id: 1,
      name: 'Usados',
    },
    {
      id: 2,
      name: 'Sellados',
    },
    {
      id: 3,
      name: 'Accesorios',
    },
  ];
  
  export const productsDestacados = [
    {
      id: 1,
      name: 'iPhone 14',
      description: 'Última versión del iPhone con una cámara mejorada y batería de larga duración.',
      price: 999,
      colors:['Black', 'White', 'Desert'],
      images: ['/products/iphone1.png','/products/iphone2.png'],
      category: 1,
      capacity: "128GB",
    },
    {
      id: 2,
      name: 'iPhone 13 Pro',
      description: 'Potente rendimiento y excelente pantalla Super Retina XDR.',
      price: 1099,
      colors:['Black', 'White', 'Desert'],
      images: ['/products/iphone2.png'],
      category: 2,
      capacity: "128GB",
    },
    {
      id: 3,
      name: 'iPhone SE 2022',
      description: 'El iPhone más accesible con el poder de un chip A15 Bionic.',
      price: 399,
      colors:['Black', 'White', 'Desert'],
      images: ['/products/iphone3.png'],
      category: 1,  
      capacity: "128GB",
    },
  ];
  
  export const productsAll = [
    {
      id: 1,
      name: 'iPhone 14',
      description: 'Última versión del iPhone con una cámara mejorada y batería de larga duración.',
      price: 999,
      colors:['Black', 'White', 'Desert'],
      images: ['/products/iphone1.png','/products/iphone2.png'],
      category: 1,
      capacity: "128GB",
    },
    {
      id: 2,
      name: 'iPhone 13 Pro',
      description: 'Potente rendimiento y excelente pantalla Super Retina XDR.',
      price: 1099,
      colors:['Black', 'White', 'Desert'],
      images: ['/products/iphone2.png'],
      category: 2, 
      capacity: "128GB",
    },
    {
      id: 3,
      name: 'iPhone SE 2022',
      description: 'El iPhone más accesible con el poder de un chip A15 Bionic.',
      price: 399,
      colors:['Black', 'White', 'Desert'],
      images: ['/products/iphone3.png'],
      category: 1,
      capacity: "256GB",
    },
    {
      id: 4,
      name: 'iPhone 14',
      description: 'Última versión del iPhone con una cámara mejorada y batería de larga duración.',
      price: 999,
      colors:['Black', 'White', 'Desert'],
      images: ['/products/iphone1.png'],
      category: 2,
      capacity: "256GB",
    },
    {
      id: 5,
      name: 'iPhone 13 Pro',
      description: 'Potente rendimiento y excelente pantalla Super Retina XDR.',
      price: 1099,
      colors:['Black', 'White', 'Desert'],
      images: ['/products/iphone2.png'],
      category: 2, 
      capacity: "256GB",
    },
    {
      id: 6,
      name: 'iPhone SE 2022',
      description: 'El iPhone más accesible con el poder de un chip A15 Bionic.',
      price: 399,
      colors:['Black', 'White', 'Desert'],
      images: ['/products/iphone3.png'],
      category: 1, 
      capacity: "256GB",
    },
    {
      id: 7,
      name: 'AirPods Pro',
      description: 'Auriculares inalámbricos con cancelación activa de ruido.',
      price: 249,
      colors:['Black', 'White', 'Desert'],
      images: ['/products/airpods_pro.png'],
      category: 3,
      capacity: "256GB",
    },
    {
      id: 8,
      name: 'Apple Watch Series 7',
      description: 'Reloj inteligente con pantalla más grande y resistente.',
      price: 399,
      colors:['Black', 'White', 'Desert'],
      images:[ '/products/apple_watch.png'],
      category: 3, 
      capacity: "256GB",
    },
    {
      id: 9,
      name: 'Cargador MagSafe',
      description: 'Cargador inalámbrico para iPhone 12 y versiones posteriores.',
      price: 39,
      colors:['Black', 'White', 'Desert'],
      images: ['/products/magsafe_charger.png'],
      category: 3,
      capacity: "256GB",
    },
    {
      id: 10,
      name: 'iPhone 14',
      description: 'Última versión del iPhone con una cámara mejorada y batería de larga duración.',
      price: 999,
      colors:['Black', 'White', 'Desert'],
      images: ['/products/iphone1.png'],
      category: 2, 
      capacity: "256GB",
    },
    {
      id: 11,
      name: 'iPhone 13 Pro',
      description: 'Potente rendimiento y excelente pantalla Super Retina XDR.',
      price: 1099,
      colors:['Black', 'White', 'Desert'],
      images: ['/products/iphone2.png'],
      category: 1, 
      capacity: "256GB",
    },
    {
      id: 12,
      name: 'iPhone SE 2022',
      description: 'El iPhone más accesible con el poder de un chip A15 Bionic.',
      price: 399,
      colors:['Black', 'White', 'Desert'],
      images: ['/products/iphone3.png'],
      category: 1,
      capacity: "256GB",
    },
  ];
  